JOB_PROFILE = [
    'BACKEND DEVELOPER',
    'FRONTEND DEVELOPER',
    'ANDROID DEVELOPER',
    'GRAPHICS DESIGNER',
    'UI/UX DESIGNER'
]

JOB_TYPE = [
    'FULL TIME',
    'PART TIME',
    'INTERNSHIP'
]